### ISSUE TITLE
Please make one for blazepose also.

### ISSUE THREAD

**Issue by saurabh1043** [terryky/tfjs_webgl_app#1]

**Comment by terryky** [comment]
I have implemented [blazepose tfjs port](https://github.com/terryky/tfjs_webgl_app/tree/master/blazepose) based on [this repository](https://github.com/terryky/tflite_gles_app/tree/master/gl2blazepose).

**Comment by saurabh1043** [comment]
Thank you so much @terryky for the port. It's very easy to understand and implement. Initially I was having some issues with running it on the webcam feed. Later, I've solved those issues and it's working perfectly now. I'll probably send a pull request containing the problems I faced and the solution.
