### ISSUE TITLE
Question: BlazePose fullbody z coordinates

### ISSUE THREAD

**Issue by moganesyan** [terryky/tfjs_webgl_app#3]
Hey!

First of all, thank you very much for sharing your work, it has helped guide my project more than you can know. 

I have a question about full body joint estimation. 

If I'm not wrong, the landmark model provides (x,y,z) triplets as outputs. However you only seem to be using the (x,y) coordinates in post processing and drawing of joint key points. Why is that? Shouldn't one be computing a 2D projection using the z dimension as well?

Thanks in advance!

**Comment by terryky** [comment]
Yes, that's correct.
The reason I discard the z value is described [google mediapipe blog](https://google.github.io/mediapipe/solutions/pose).
```
Note that the z value should be discarded as the model is currently not fully trained to predict depth, but this is something we have on the roadmap. 
```
